### ISSUE TITLE
build app osx64

### ISSUE THREAD

**Issue by stefano055415** [nwjs/nw-builder#269] opened 2015-11-17 09:28 UTC
At startup "powerpc not supported"??????

nwjs version 0.12.3

it's the same for 0.13.0

**Comment by adam-lynch** [comment] 2015-12-06 00:42
I have no idea sorry. Does this happen when running your app using the `nw` module too? Or is it only happening with nw-builder?

**Comment by JBeen** [comment] 2015-12-09 19:34
I have the same problem. Only when build app and then trying to start it. But work well when start program without building: nwbuild -r "MyApp"

**Comment by dotsonjb14** [comment] 2015-12-11 21:09
Same thing here the nw command works nwbuild -r works but the build itself doesn't

**Comment by adam-lynch** [comment] 2015-12-18 14:27
Are you specifying an NW.js version in the options?

**Comment by adam-lynch** [comment] 2015-12-18 14:27
Are you specifying an NW.js version in the options?

**Comment by JBeen** [comment] 2015-12-23 21:03
Yes, it was my second attempt, after all I'm trying to specify version (different), but always some files were missed, depends of version.

**Comment by JBeen** [comment] 2015-12-23 21:15
Now I'm was doing another try (nw-builder updated to 2.2.0):
1. Built application without specifying version, so using v0.13.0-alpha7. On start I had message: "You can’t open the application “hello-world.app” because it may be damaged or incomplete."
2. Then specified version: nwbuild -p osx64 -v 0.12.3. And received building error: "Error: ENOENT: no such file or directory, stat '/Users/hello-world/osx64/hello-world.app/Contents/Resources/app.icns']"
3. -v 0.12.2 -- message on starting application: "You can’t open the application “hello-world.app” because PowerPC applications are no longer supported."
4. -v 0.12.1 -- [Error: ENOENT: no such file or directory, lstat '/Users/hello-world/osx64/hello-world.app/Contents/Resources/app.nw/hello-world/osx64/hello-world.app/Contents/Resources/missingImage.png']

**Comment by marty-krishner** [comment] 2016-01-13 04:54
+1

**Comment by noah-sis** [comment] 2016-06-21 15:56
+1

**Comment by adam-lynch** [comment] 2016-07-02 20:44
Could someone supply a sample project for this please?

**Comment by matthew-dean** [comment] 2016-09-09 23:49
I got this error after I created a new user on my Macbook, and logged in with that user, then tried to launch my NW.js application. It runs under one user, but not another. So, definitely seems like a permissions issue on the generated executable?

**Comment by adam-lynch** [comment] 2016-09-12 20:13
@matthew-dean sounds mad. Can you share the permissions of the generated executable from both accounts?

**Comment by matthew-dean** [comment] 2016-09-13 02:53
@adam-lynch It's a dupe of #289 (or 289 is a dupe of this, however you want to look at it). Same steps listed at the beginning of the issue.

**Comment by adam-lynch** [comment] 2016-09-15 14:42
OK thanks @matthew-dean I'll close this so.

**Closed by adam-lynch** 2016-09-15 14:42 UTC
Labels: support
