### ISSUE TITLE
Support beta

### ISSUE THREAD

**Issue by Sytten** [nwjs/nw-builder#285] opened 2016-01-11 02:56 UTC
Hi,

I would like to know if you will support the beta release of NWJS, because currently I get all sorts of errors when I try to build with the version 0.13.0...

Thanks!

**Comment by kucix** [comment] 2016-01-28 13:01
+1

**Comment by janviehweger** [comment] 2016-02-17 18:30
+1

**Comment by janviehweger** [comment] 2016-02-17 18:42
this should work:
`nwbuild -r -v 0.13.0-beta6 .`
it pulls the files from http://dl.nwjs.io/v0.13.0-beta6/. 
the problem is, that you only get what they call the "normal" version - no "sdk" or "nacl".
should be not that difficult to hack the scrapePtrn in nw-builder/lib/versions.js

**Comment by gitawego** [comment] 2016-02-17 22:04
yeah. hope the build flavors option could be supported soon

**Comment by Sytten** [comment] 2016-02-25 20:12
I will check to modify my script, I forked an app that use gulp with a coffeescript script, I guess I will have to rewrite it (anyway who the f*ck use coffeescript)

**Comment by gitawego** [comment] 2016-02-29 08:04
@Sytten for your convenience ^^ http://js2.coffee/

**Comment by Sytten** [comment] 2016-02-29 08:11
Thanks! Still I cant build my app with the beta, nwbuilder needs a proper update. Meanwhile I will continue to use 0.12.3...

**Comment by adam-lynch** [comment] 2016-03-11 17:15
Closing since we already have #275. I'd love any help I could get :+1:

**Closed by adam-lynch** 2016-03-11 17:15 UTC
