### ISSUE TITLE
OSX 10.10 - V12 & 13 32 & 64 bit won't run at all

### ISSUE THREAD

**Issue by diginfo** [nwjs/nw-builder#268] opened 2015-11-17 07:58 UTC
I have tried compiling 0.13.0-alpha5 64bit and both 32 and 64 bit for OSX versions 0.12.3 and 0.12.2 and neither will run with an error message:

    You can’t open the application “nwjs” because it is not supported on this type of Mac.

However, if I compile 0.8.6 then I can get the 32 bit version to run.

Also, the strange thing is when I compile 64 bit, the file name is nwjs.app, however the 32 bit has the correct file name as stated in the package.json file.

What's wrong ??

**Comment by adam-lynch** [comment] 2015-12-06 01:31
Alpha builds aren't supported right now. It's a bug that you're even able to get it. 

I'm not sure what's up with 0.12.x for you. Are you on old version of OS X or anything like that?

**Comment by diginfo** [comment] 2015-12-06 01:33
I am on the latest version of OSX,  0.12.3 and 0.12.2 both have the same error ?!

**Comment by adam-lynch** [comment] 2015-12-06 01:35
Hmm, I've never seen this before. Does this happen with a simple app? Like with a simple index.html and manifest file? Does your app run ok with the `nw` module?

**Comment by diginfo** [comment] 2015-12-06 01:36
Yes, all the manifest had was a single package.json file, nothing else.

**Comment by adam-lynch** [comment] 2015-12-06 01:37
Could you share your app?

**Comment by diginfo** [comment] 2015-12-06 01:39
This was several weeks ago, I will need to reconstruct it, will try and do that today.

**Comment by adam-lynch** [comment] 2015-12-06 01:39
Ok cool

**Comment by diginfo** [comment] 2015-12-08 12:03
Ok, I have solved this, the cause was permissions on the build folders.

Once I had changed permissions everything worked.

It might be worthwhile including this option or prompting the user to let them know.

**Comment by adam-lynch** [comment] 2015-12-08 16:20
Which folders?

**Comment by diginfo** [comment] 2015-12-10 09:54
Well it's actually the .app files, but I just changed all of the build folders that contain the various os built versions to 777.

**Comment by adam-lynch** [comment] 2015-12-18 14:33
Hmm...

**Comment by adam-lynch** [comment] 2016-07-02 20:46
Closing as a duplicate of #289. Correct me if I'm wrong.

**Closed by adam-lynch** 2016-07-02 20:46 UTC
Labels: enhancement
