### ISSUE TITLE
EMFILE or ENOENT when building for osx

### ISSUE THREAD

**Issue by jthrilly** [nwjs/nw-builder#180] opened 2015-02-03 23:01 UTC
For my app building for win32 and win64 works fine, but building for any osx platform will result in either an EMFILE or ENOENT error.

I'm running Yosemite 10.10.2, so having the usual trouble with ulimit not working. However, launchctl limit maxfiles reports:
	maxfiles    10240          10240   
and ulimit -n reports 1024.

Examples of errors:

```
joshua@why ~> node /usr/local/bin/nwbuild -p osx64 ~/Sites/networkCanvas/ -o ~/Sites/networkCanvas/build/
Latest Version: v0.12.0-alpha2
Using v0.12.0-alpha2
Create cache folder in /usr/local/lib/node_modules/node-webkit-builder/cache/0.12.0-alpha2
Using cache for: osx64
Create release folder in /Users/joshua/Sites/networkCanvas/build/networkCanvas/osx64
[ { [Error: EMFILE, open '/Users/joshua/Sites/networkCanvas/build/networkCanvas/osx64/networkCanvas.app/Contents/Resources/app.nw/bower_components/jquery-ui/ui/effect-size.js']
    errno: 20,
    code: 'EMFILE',
    path: '/Users/joshua/Sites/networkCanvas/build/networkCanvas/osx64/networkCanvas.app/Contents/Resources/app.nw/bower_components/jquery-ui/ui/effect-size.js' } ]
```

```
joshua@why ~> node /usr/local/bin/nwbuild -p osx64 ~/Sites/networkCanvas/ -o ~/Sites/networkCanvas/build/
Latest Version: v0.12.0-alpha2
Using v0.12.0-alpha2
Create cache folder in /usr/local/lib/node_modules/node-webkit-builder/cache/0.12.0-alpha2
Using cache for: osx64
Create release folder in /Users/joshua/Sites/networkCanvas/build/networkCanvas/osx64
{ [Error: ENOENT, no such file or directory '/Users/joshua/Sites/networkCanvas/build/networkCanvas/osx64/networkCanvas.app/Contents/Resources/app.nw/README.html']
  errno: 34,
  code: 'ENOENT',
  path: '/Users/joshua/Sites/networkCanvas/build/networkCanvas/osx64/networkCanvas.app/Contents/Resources/app.nw/README.html',
  syscall: 'lstat' }
```

**Comment by adam-lynch** [comment] 2015-02-06 15:04
Which version of node-webkit-builder have you?

**Comment by jthrilly** [comment] 2015-02-09 00:30
I'm afraid I can't access the version number because of the line endings issue reported elsewhere. No matter which way I call the file from terminal, I get env: node\r: No such file or directory

Sorry I can't be more useful!

**Comment by adam-lynch** [comment] 2015-02-09 20:20
@jthrilly you can see in `node_modules/node-webkit-builder/package.json`

**Comment by danielhusar** [comment] 2015-02-13 10:08
I have exactyl same error, my version of `node-webkit-builder` is `1.0.8`

**Comment by brian-mann** [comment] 2015-02-13 20:58
I am also receiving the identical error message with version `1.0.8`

**Comment by mario-deluna** [comment] 2015-02-16 10:34
Same here for `1.0.8`.

**Comment by Deliaz** [comment] 2015-02-17 15:57
Have the same (`1.0.8`)
But it happens not on Mac Os only. If I build app for Mac on Windows 8.1, output is:
![bug](https://api.monosnap.com/rpc/file/download?id=Mk4jlFJIb1ZrVWb9O1qFQYEnvOPn9w)

So, I get successful build, if exclude 'jquery' module from files to build.

**Comment by elliotbonneville** [comment] 2015-02-21 00:26
Experiencing the same issue as well.

**Comment by adam-lynch** [comment] 2015-02-23 21:55
Could someone try again with 1.0.10?

**Comment by gihrig** [comment] 2015-02-24 06:59
1.0.10 fixed this issue for me, I guess. My app now builds for OS X (OS X 10.10.2) without error, but it does not execute.

On execution, console log shows:

`com.apple.xpc.launchd[1]: (com.node-webkit-builder.icrumz.291132[939]) Service exited with abnormal code: 1`

May be unrelated, I'm still researching

**Comment by philipproplesch** [comment] 2015-02-24 09:47
I can confirm that 1.0.10 solved this issue for me on Windows :+1:

**Comment by danielhusar** [comment] 2015-02-24 09:59
For me it works fine now on osx. Thanks.

**Comment by adam-lynch** [comment] 2015-03-07 15:51
Closing. I'll reopen if this happens for anyone still.

**Comment by benjismith** [comment] 2015-03-07 16:24
I just updated to 1.0.11 this morning, and I'm still seeing EMFILE errors during my build. I'm on Mac OS X Yosemite 10.10.2.

**Comment by adam-lynch** [comment] 2015-03-07 16:35
![cries](http://media.giphy.com/media/YLgIOmtIMUACY/giphy.gif)

**Comment by benjismith** [comment] 2015-03-07 17:58
There there... It will all be better someday :)

Let me know if there's anything I can do to help. Do you need any logfiles or anything?

**Comment by kessler** [comment] 2015-03-08 10:58
@benjismith Is the error consistent (i.e happens every time)?

**Comment by benjismith** [comment] 2015-03-08 16:58
Yes, it happens every time.

**Comment by kessler** [comment] 2015-03-08 17:05
Is is possible for you to paste your package.json here, specifically the dependencies?

**Comment by benjismith** [comment] 2015-03-08 17:08
```
{
  "name": "MyApplication",
  "version": "0.0.1",
  "private": true,
  "main": "app/index.html",
  "single-instance" : true,
  "window": {
    "width": 1280,
    "height": 750,
    "toolbar": false
  },
  "dependencies": {
    "MD5": "latest",
    "moment": "latest",
    "hogan.js": "latest",
    "lodash-node": "latest",
    "mkdirp": "latest",
    "form-data" : "latest",
    "node-webkit-updater" : "latest"
  },
  "devDependencies": {
    "gulp": "^3.8.11",
    "gulp-util": "^3.0.4",
    "node-webkit-builder": "^1.0.11"
  }
}
```

**Comment by kessler** [comment] 2015-03-09 10:55
So the builder sits in the same directory as the application? (you have one or two package.json)

**Comment by benjismith** [comment] 2015-03-10 00:05
It looks like this:

```
MyApplication/package.json
MyApplication/GulpFile.js
MyApplication/app/index.html
MyApplication/app/main.js
MyApplication/app/vendor/          # jquery, bootstrap, various other client-side libs (~1500 files)
MyApplication/app/styles/          # app-specific css (~20 files)
MyApplication/app/lib/             # app-specific javascript (~100 files)
```

**Comment by kessler** [comment] 2015-03-10 09:57
Was hoping you'll have two. In any case, can you try deleting all the non dev dependencies and run the build?

**Comment by benjismith** [comment] 2015-03-10 19:58
I tried deleting the dependencies and building again, and it doesn't help. I also tried building on windows, and that doesn't help either.

It seems like the root cause of the problem here is trying to simultaneously copy thousands of files using async operations. Is that really necessary? Is there any advantage? Why not just loop through the files and copy them synchronously, one at a time?

**Comment by agozie** [comment] 2015-03-12 08:30
Same EMFILE error on version 1.1.0, on Yosemite and Ubuntu 14.10.

**Comment by chino23** [comment] 2015-03-12 09:39
Same here OSX 10.10.2 and node-webkit-builder 1.0.11. 

Had the EMFILE error 20, then after updating node to 0.12.0 and npm to 2.7.0 I have the same error, but with error number -24

My app folder has 2063 files. Interesting, cause I have some npm scripts and gulp scripts that copy the whole folder and this never happens.

**Comment by adam-lynch** [comment] 2015-03-12 17:04
@chino32 try the latest one

**Comment by chino23** [comment] 2015-03-13 04:31
hmm @adam-lynch am I missing something? :) I'm already using the latest version of node-webkit-builder, and there hasn't been any changes in the last 24 hours as I can see.

**Comment by adam-lynch** [comment] 2015-03-13 10:55
My mistake, @chino23. I was thinking the latest was `1.1.0`.

**Comment by fernandogrd** [comment] 2015-03-13 15:05
Same here, Linux 3.18.6, node-webkit-builder 1.0.11.
I had to raise ulimit to 8192 to be able to run, but I would like to run on a CI environment where I don't have permissions to change ulimit (there the ulimit is 4096)

**Comment by bastimeyer** [comment] 2015-03-14 10:59
Could this be related to #204 ?

**Comment by eugirdor** [comment] 2015-05-18 16:46
I started getting ENFILE errors after adding a particularly large library to my project.  I have traced down the issue and it appears to be caused by this code in NwBuilder.mergeAppFiles():

https://github.com/mllrsohn/node-webkit-builder/blob/ecc96607491212c6568c0753847dc622255889d4/lib/index.js#L433-L442

If I understand the code correctly, that line attempts to copy every file in the project simultaneously.  You might get lucky enough for some of the files to finish before it starts more, but eventually, you will hit the limit of how many open files you can have.  I made a fix locally, limiting the number of concurrent copies and no longer have the issue.

@adam-lynch If you don't mind bluebird being updated to 2.x.x, I can submit a PR (I use the 2.0 `concurrency` option in `Promise.map` for my fix.)

**Comment by chino23** [comment] 2015-05-19 02:33
I would love a fix for that!

**Comment by mmfilesi** [comment] 2016-01-10 10:11
Similar error, sorry. Windows 64.
```
Running "nwjs:src" (nwjs) task
Latest Version: v0.13.0-beta2
Using v0.13.0-beta2
Create cache folder in c:\Users\marcos\documents\jsLabs\library\cache\0.13.0-beta2
Downloading: http://dl.nwjs.io/v0.13.0-beta2/nwjs-v0.13.0-beta2-win-ia32.zip
Create cache folder in c:\Users\marcos\documents\jsLabs\library\cache\0.13.0-beta2
Downloading: http://dl.nwjs.io/v0.13.0-beta2/nwjs-v0.13.0-beta2-win-x64.zip
                                                downloading [====---------------  downloading [====================] 100% 0.0s

Create release folder in c:\Users\marcos\documents\jsLabs\library\webkitbuilds\library\win32
Create release folder in c:\Users\marcos\documents\jsLabs\library\webkitbuilds\library\win64
Fatal error: ENOENT: no such file or directory, lstat 'c:\Users\marcos\documents\jsLabs\library\cache\0.13.0-beta2\win32\ffmpegsumo.dll'
```
package.json
```
  "devDependencies": {
    "grunt": "^0.4.5",
    "grunt-nw-builder": "^2.0.0",
    "load-grunt-tasks": "^3.4.0",
    "nw": "^0.12.3",
    "nw-builder": "^2.2.0"
  }
```

**Comment by adam-lynch** [comment] 2016-01-10 10:31
@mmfilesi see #275. Specify a non-alpha version and should be fine.

**Comment by mmfilesi** [comment] 2016-01-10 14:56
I @adam-lynch, ty.

I try now with "nw": "0.12.2",

but the result...

Fatal error: ENOENT: no such file or directory, lstat 'c:\Users\marcos\documents\jsLabs\libr\cache\0.13.0-beta2\win32\ffmpegsumo.dll'

**Comment by adam-lynch** [comment] 2016-01-10 16:44
@mmfilesi oh no, what I mean is when you're calling `nw-builder`, you need to pass a version;

```javascript
var NwBuilder = require('nw-builder');
var nw = new NwBuilder({
    files: './path/to/nwfiles/**/**', // use the glob format
    platforms: ['osx32', 'osx64', 'win32', 'win64'],
    version: '0.12.2'
});
```

That should work fine.

**Comment by mmfilesi** [comment] 2016-01-10 22:33
Thats work fine : )  : )  : )

Ty adam-lynch, !!!!

**Comment by adam-lynch** [comment] 2016-07-02 20:51
I haven't heard about this problem in a long long time. I think it's ok. Fixes have also been released today by the way (newer NW.js versions are support, alpha/beta builds, etc.)

**Closed by adam-lynch** 2016-07-02 20:51 UTC
Labels: bug
