### ISSUE TITLE
Build Folder Not Found

### ISSUE THREAD

**Issue by cupofnestor** [nwjs/nw-builder#406] opened 2016-12-13 22:07 UTC
I'm getting `ENOENT` when building with grunt-nw-builder as well as nwbuild.
nwbuild is looking for my platform-specific build folder as '/osx64' where in practice the folder is titled with the version string.  

That is: 
   `/builds/nw-demo/osx64/nw-demo.app/Contents/Info.plist` -- does not exist
   `/builds/nw-demo/nwjs-sdk-v0.19.2-osx-x64/nw-demo.app/Contents/Info.plist` -- exists
```
Latest Version: v0.19.2
Using v0.19.2 (sdk)
Create cache folder in /Path/To/My/Project/cache/0.19.2-sdk
Downloading: http://dl.nwjs.io/v0.19.2/nwjs-sdk-v0.19.2-osx-x64.zip
  downloading [====================] 100% 0.0s

Create release folder in /Path/To/My/Project/cache/builds/nw-demo/osx64
{ [Error: ENOENT: no such file or directory, open '/Path/To/My/Project/cache/builds/nw-demo/osx64/nw-demo.app/Contents/Info.plist']
  cause: 
   { [Error: ENOENT: no such file or directory, open '/Path/To/My/Project/cache/builds/nw-demo/osx64/nw-demo.app/Contents/Info.plist']
     errno: -2,
     code: 'ENOENT',
     syscall: 'open',
     path: '/Path/To/My/Project/cache/builds/nw-demo/osx64/nw-demo.app/Contents/Info.plist' },
  isOperational: true,
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Path/To/My/Project/cache/builds/nw-demo/osx64/nw-demo.app/Contents/Info.plist' }

```

**Comment by StanleyTian** [comment] 2017-02-02 01:09
Having the same problem

**Comment by adam-lynch** [comment] 2017-02-12 01:18
I'm closing this as I can't reproduce. If you still can, let me know and we'll look into it further.

**Closed by adam-lynch** 2017-02-12 01:18 UTC
