### ISSUE TITLE
Wrong Permissions...

### ISSUE THREAD

**Issue by Geyup** [nwjs/nw-builder#276] opened 2015-12-06 06:25 UTC
Someone over at the PopcornTime CE mentioned that nw-builder might be this issue for wrong permissions;

https://github.com/PopcornTimeCE/desktop/issues/22

When I compile PopcornTime CE in Linux I'm seeing these that I mentioned in the issue as executable.

Is this a problem with nw-builder causing this?

thank you

**Comment by adam-lynch** [comment] 2015-12-06 13:42
That could easily be true. I know there's some chmodding done in nw-builder. Would you mind having a look at the code and maybe make a PR? :smile:

**Comment by Geyup** [comment] 2015-12-07 07:00
I'm not a coder, and I'm clueless with this sort of code, c stuff maybe I could handle.

**Comment by adam-lynch** [comment] 2015-12-07 09:54
No problem. So could you tell me exactly what you'd expect the permissions to be?

**Comment by Geyup** [comment] 2015-12-07 22:24
I would of thought they would be 644 since they are files, and not apps or scripts that call to be executlable/run...

Because in the original version of Popcorn Time when I compiled it they were 644, but for some reason when building this new community version they are turning out executable.

And I thought both versions of Popcorn Time were using nw-builder...

**Comment by adam-lynch** [comment] 2015-12-18 14:31
The Popcorn Time issue link is 404ing :/

**Comment by adam-lynch** [comment] 2015-12-18 14:32
http://webcache.googleusercontent.com/search?q=cache:https://github.com/PopcornTimeCE/desktop/issues/22 :smile:

**Comment by Geyup** [comment] 2015-12-19 01:06
Seems as though the MPAA has everyone on the run, so everytime you turn around a repo is up a repo is down, or someone else is taking over or backing up the project...

I'll let you know once this is backup and going again...

thanks

**Comment by Geyup** [comment] 2015-12-19 01:08
Actually this is the repo;

https://github.com/PopcornTime-CE/desktop

**Comment by adam-lynch** [comment] 2016-07-02 20:46
Closing as a duplicate of #289. Correct me if I'm wrong.

**Closed by adam-lynch** 2016-07-02 20:46 UTC
Labels: bug
