### ISSUE TITLE
Builds empty nw:blank app on Windows/Linux

### ISSUE THREAD

**Issue by nolanlawson** [nwjs/nw-builder#107] opened 2014-11-10 15:50 UTC
This was already filed on grunt-node-webkit-builder, but I think it might be more appropriate in this repo: https://github.com/mllrsohn/grunt-node-webkit-builder/issues/117.

Anybody seen this issue? Basically Windows and Linux are unbuildable. :(

**Comment by rlee1121** [comment] 2015-01-13 20:14
@adam-lynch Can you provide a little more detail as to how you got your Windows build working (versions, options for NwBuilder instance, etc.)? Experiencing the same issue ("nw:blank" loading) with the following:

node-webkit: 0.11.5,
node-webkit-builder: 1.0.4

var nw = new NwBuilder({
    appName: pkg.displayName,
    appVersion: pkg.version,
    files: includes,
    platforms: ["win", "osx"],
    version: "0.11.5",
    macIcns: pkg.macIcon,
    macCredits: pkg.macCredits,
    macZip: true,
    macPlist: {
        'NSHumanReadableCopyright': "\© 2014"
    }
    winIco: pkg.winIcon
});

**Comment by Thomas-B** [comment] 2015-01-16 15:47
@rlee1121 
I experienced the same issue and resolved it by removing a module which was really deep.
As @adam-lynch  said [here](https://github.com/mllrsohn/grunt-node-webkit-builder/issues/117#issuecomment-61432613) it might be related to path's length.

**Comment by adam-lynch** [comment] 2015-01-16 15:55
@rlee1121 try Path Length Checker which I mentioned in the issue @Thomas-B linked to. (Thanks @Thomas-B)

**Comment by rlee1121** [comment] 2015-01-16 18:20
@Thomas-B @adam-lynch thanks so much for the suggestions, this was indeed the issue!

**Comment by marbemac** [comment] 2015-02-23 22:48
I'm also running into this issue - nw:blank on Windows. I'm using Sails.js, and I think I'm running into the path name length issue described above. However.. I can't just leave sails out of the node_modules folder - it's required for my app to function. Does anybody have any suggestions, other than removing whichever modules include long path names? Thanks!

**Comment by adam-lynch** [comment] 2015-02-23 22:54
@marbemac Let's say there is one module which is a dependency of Sails.js which is a cause of long paths. An example path: `node_modules/Sails.js/node_modules/a/node_modules/b/.../node_modules/z.js`. 

Manually `npm install --save g` (`g` or a module a good bit down the `node_modules` tree which is still under 256 characters), then delete the `node_modules/Sails.js` directory and re-install it. That way, it shouldn't install `g` and all of `g`'s own dependencies inside `node_modules/Sails.js/node_modules/a/.../f/node_modules` anymore.

**Comment by marbemac** [comment] 2015-02-24 19:41
@adam-lynch It's a pain, but that works, thanks! :+1: The endless nesting in npm is tiresome.

**Comment by adam-lynch** [comment] 2015-03-07 16:05
@nolanlawson still a problem with the latest version?

**Comment by Nitemaeric** [comment] 2015-03-20 19:21
@adam-lynch Is there any way to simplify this process? Is the 256 character length path a windows hard limitation?

**Comment by adam-lynch** [comment] 2015-03-20 19:31
@Nitemaeric Not really, no. There are node modules out there for flattening your dependencies but as far as I know they're not reliable, because if two modules depend on two different versions of the same module, then they'll probably just take one version and discard the other.

Yeah, more info here: http://stackoverflow.com/questions/1880321/why-does-the-260-character-path-length-limit-exist-in-windows.

**Comment by Nitemaeric** [comment] 2015-03-21 08:13
@adam-lynch Ok, thanks! I should get to flattening my dependencies then!

**Comment by MarcFowler** [comment] 2015-04-08 11:36
I ran into this exact issue and it was a nightmare! I tried to do things manually but I had a whole bunch of problems with that, as my dependencies were pretty complex.

In the end, I figured it out by using https://www.npmjs.com/package/flatten-packages

As you said @adam-lynch, it does discard multiple versions of the same but as it happens, that was okay for me. It took some manual jiggering around but this does at least seem to be the cause and I thought I'd share what worked for me!

**Comment by adam-lynch** [comment] 2015-07-02 13:31
Everyone, see [Dealing with long paths](http://engineroom.teamwork.com/dealing-with-long-paths/)

**Comment by seiyria** [comment] 2015-10-10 21:48
npm@3 might also help this situation. It installs flat instead of nested by default, then nests when there is a version conflict.

**Comment by adam-lynch** [comment] 2016-07-01 21:33
Closing this as I'm hoping the replies helped above or it's now solved as of npm@3

**Closed by adam-lynch** 2016-07-01 21:33 UTC
